/**
 * Landing-page copy in English and Kiswahili. The page component is the
 * same for both; only this dictionary changes, so the two never drift.
 */
export type Locale = 'en' | 'sw'

export interface LandingCopy {
  kicker: string
  h1a: string
  h1b: string
  lead: string
  ctaDemo: string
  ctaTry: string
  ctaStart: string
  stats: [string, string][]
  madeForHere: { kicker: string; title: string; items: { title: string; body: string }[] }
  modules: { kicker: string; title: string; more: string; groups: { title: string; items: { name: string; note: string }[] }[] }
  documents: { kicker: string; title: string; lead: string; items: { title: string; body: string }[] }
  steps: { kicker: string; title: string; items: [string, string][] }
  trust: { kicker: string; title: string; lead: string; items: [string, string][] }
  pricing: { kicker: string; title: string; body: string; hint: string; cta: string }
  faq: { kicker: string; title: string; items: [string, string][] }
  finalCta: { title: string; body: string; whatsapp: string; demo: string }
}

export const COPY: Record<Locale, LandingCopy> = {
  en: {
    kicker: 'Mfumo wa usimamizi wa shule · Tanzania',
    h1a: 'Run the whole term',
    h1b: 'from one place.',
    lead: 'Registers, marks, fees in shillings, SMS to parents, report cards that print, payroll with PAYE and NSSF, and proper accounts — built for how Tanzanian private schools actually work, from nursery to Form 6.',
    ctaDemo: 'Book a demo on WhatsApp',
    ctaTry: 'Try the demo school',
    ctaStart: 'Start free with 50 pupils',
    stats: [['25+', 'modules'], ['7', 'user roles'], ['EN · SW', 'languages']],
    madeForHere: {
      kicker: 'Made for here',
      title: 'Not a foreign system with the currency changed.',
      items: [
        { title: 'Terms, NECTA grades, divisions', body: 'Academic years split into terms; marks combine CAT and end-of-term by your weights; A–F bands and points; Division I–IV on the best seven, the way NECTA does it. Report cards leave a space for the head teacher to sign.' },
        { title: 'Shillings and mobile money', body: 'Fees are billed and receipted in TZS — whole shillings, no rounding. Record M-Pesa, Tigo Pesa, Airtel Money, bank or cash, each with its own receipt number, and every receipt posts itself to the ledger.' },
        { title: 'SMS reaches the wazazi', body: 'Parents get a text, not an email they will never open. Broadcast to a class or the whole school, in Kiswahili or English, and see the segment cost before you send.' },
      ],
    },
    modules: {
      kicker: 'Everything a school does',
      title: 'From the register to the balance sheet.',
      more: 'Full feature list',
      groups: [
        { title: 'Academics', items: [{ name: 'Attendance', note: 'Daily register, teacher home shows what is still unmarked' }, { name: 'Exams & mark sheets', note: 'Enter → submit → review → publish → lock' }, { name: 'Class results', note: 'Rankings, subject analysis, divisions, remarks' }, { name: 'Report cards', note: 'Configurable grading and layout, PDF per class' }] },
        { title: 'Teaching', items: [{ name: 'Teacher portal', note: 'Teaching load decides what each teacher sees' }, { name: 'Timetable', note: 'Drag and drop, clash detection, teacher week' }, { name: 'Seating plans', note: 'Drag pupils onto desks, print the chart' }, { name: 'Homework & notes', note: 'Posted to the class, seen by parents and pupils' }] },
        { title: 'Parents & pupils', items: [{ name: 'Parent portal', note: 'Progress, fees, homework, published results' }, { name: 'Messages', note: 'Teacher ↔ parent, always about one pupil' }, { name: 'SMS & notices', note: 'Class or school-wide, cost shown first' }, { name: 'ID cards', note: 'CR80 with photo and QR verification' }] },
        { title: 'Money & staff', items: [{ name: 'Fees', note: 'Structures, receipts, statements, debtors ageing' }, { name: 'Accounting', note: 'Double-entry ledger, income statement, balance sheet' }, { name: 'HR & payroll', note: 'Leave, staff attendance, PAYE/NSSF payslips' }, { name: 'Library, hostel, transport', note: 'The rest of running a school' }] },
      ],
    },
    documents: {
      kicker: 'What comes out of the printer',
      title: 'Documents a school actually hands over.',
      lead: 'Every one of these is generated by Shule SMS from the demo school — no mock-ups.',
      items: [
        { title: 'Report card', body: 'Weighted marks, grade, points, position, division, class average, remarks and signature lines.' },
        { title: 'Class results sheet', body: 'Every pupil and subject on one landscape page, with positions and subject means.' },
        { title: 'Payslip', body: 'Basic, allowances, NSSF, PAYE on the TRA bands, net pay and employer contributions.' },
        { title: 'Student ID card', body: 'Photo, class, guardian, and a QR code that verifies the holder on any phone.' },
      ],
    },
    steps: {
      kicker: 'Getting started',
      title: 'Live before the term starts.',
      items: [
        ['Set up the school', 'Create your academic year and terms, add subjects and classes, set the grading scale. The office does this once.'],
        ['Enrol pupils, parents and teachers', 'Add pupils to their classes and attach guardians — siblings share one parent record. Give each family and each teacher a login in a click.'],
        ['Run the term', 'Teachers take the register and enter marks. The bursar records fees. Parents get an SMS. Report cards, payslips and statements print at the end.'],
      ],
    },
    trust: {
      kicker: 'Your records, kept properly',
      title: 'Built like a system of record, because it is one.',
      lead: "A school's marks and money are not test data. Every change to a grade or a payment is attributed to the person who made it, each school's data is isolated from every other, and your school is backed up every night.",
      items: [
        ['Audit trail', 'Who recorded a payment, who entered a mark, when.'],
        ['Per-school isolation', "One school can never read or change another's records."],
        ['Nightly backups', 'A full copy every night, restorable on its own; your data is exported on request.'],
        ['Read-only, never dark', 'If a subscription lapses, records stay readable while you sort it out.'],
      ],
    },
    pricing: {
      kicker: 'Pricing',
      title: 'Free for 50 pupils. Then priced for your school.',
      body: 'Paid plans are quoted from how many pupils you have and which levels you teach — nursery, primary, O-level, A-level. Billed monthly in shillings, by bank transfer or mobile money.',
      hint: 'As a guide: a 300-pupil primary school pays less per month than one term of a single pupil\'s fees. No per-user charges, nothing per report card or receipt.',
      cta: 'How pricing works',
    },
    faq: {
      kicker: 'Questions schools ask',
      title: 'Before you call.',
      items: [
        ['We keep everything in Excel. Can we bring it in?', 'Yes. Pupils, guardians, staff and fee structures import from a spreadsheet, and we do the first import with you during onboarding.'],
        ['Does it work when the internet is slow or off?', 'The pages are light enough for 3G and the app installs on a phone. If the connection drops you see an honest offline page rather than a spinner; nothing entered is lost once you are back.'],
        ['Who owns the data?', 'The school. Your data is isolated from every other school, backed up nightly, and exported to you on request — even if you leave.'],
        ['What happens if we stop paying?', 'Nothing disappears. The school goes read-only: every register, mark and receipt stays visible until the invoice is settled, and writing turns back on the same minute.'],
        ['Can we run it on our own server?', 'Yes — a standalone edition installs on a server the school controls, with no subscription and no gating. Quoted per school.'],
        ['How do parents use it?', 'Most parents just receive SMS. Those who want more get a portal login: results once published, fee balance, homework, and messages with the class teacher.'],
      ],
    },
    finalCta: { title: 'See it with your own pupils on the screen.', body: 'A demo takes thirty minutes on WhatsApp video, in Kiswahili or English. Bring last term\'s mark sheet and we will print a report card from it.', whatsapp: 'Book a demo on WhatsApp', demo: 'Open the demo school' },
  },
  sw: {
    kicker: 'Mfumo wa usimamizi wa shule · Tanzania',
    h1a: 'Endesha muhula mzima',
    h1b: 'kutoka sehemu moja.',
    lead: 'Mahudhurio, alama, ada kwa shilingi, SMS kwa wazazi, ripoti zinazochapishwa, mishahara yenye PAYE na NSSF, na hesabu za kweli — imejengwa kwa jinsi shule binafsi za Tanzania zinavyofanya kazi, kuanzia chekechea hadi kidato cha sita.',
    ctaDemo: 'Omba demo kwa WhatsApp',
    ctaTry: 'Jaribu shule ya mfano',
    ctaStart: 'Anza bure na wanafunzi 50',
    stats: [['25+', 'moduli'], ['7', 'aina za watumiaji'], ['SW · EN', 'lugha']],
    madeForHere: {
      kicker: 'Imetengenezwa kwa ajili ya hapa',
      title: 'Si mfumo wa kigeni uliobadilishwa sarafu tu.',
      items: [
        { title: 'Mihula, madaraja ya NECTA, divisheni', body: 'Mwaka wa masomo umegawanywa katika mihula; alama za CAT na mtihani wa mwisho zinaunganishwa kwa uzito unaoweka; madaraja A–F na pointi; Divisheni I–IV kwa masomo saba bora, kama NECTA. Ripoti ina nafasi ya sahihi ya mkuu wa shule.' },
        { title: 'Shilingi na pesa za simu', body: 'Ada zinatozwa na kupokelewa kwa TZS — shilingi kamili, bila kukadiria. Rekodi M-Pesa, Tigo Pesa, Airtel Money, benki au taslimu, kila moja na namba yake ya risiti, na kila risiti inaingia yenyewe kwenye leja.' },
        { title: 'SMS inawafikia wazazi', body: 'Wazazi wanapata ujumbe wa simu, si barua pepe wasiyoifungua. Tuma kwa darasa au shule nzima, kwa Kiswahili au Kiingereza, na uone gharama kabla ya kutuma.' },
      ],
    },
    modules: {
      kicker: 'Kila kitu shule inachofanya',
      title: 'Kuanzia rejista hadi mizania.',
      more: 'Orodha kamili ya huduma',
      groups: [
        { title: 'Taaluma', items: [{ name: 'Mahudhurio', note: 'Rejista ya kila siku; mwalimu anaona ambayo bado' }, { name: 'Mitihani na alama', note: 'Ingiza → wasilisha → kagua → chapisha → funga' }, { name: 'Matokeo ya darasa', note: 'Nafasi, uchambuzi wa masomo, divisheni, maoni' }, { name: 'Ripoti za wanafunzi', note: 'Madaraja na mpangilio unaoweka, PDF kwa darasa' }] },
        { title: 'Ufundishaji', items: [{ name: 'Portali ya mwalimu', note: 'Mzigo wa ufundishaji unaamua anachokiona' }, { name: 'Ratiba', note: 'Buruta na uachie, hugundua migongano, wiki ya mwalimu' }, { name: 'Mpangilio wa viti', note: 'Buruta wanafunzi kwenye madawati, chapisha' }, { name: 'Kazi za nyumbani', note: 'Zinatumwa kwa darasa, wazazi na wanafunzi wanaziona' }] },
        { title: 'Wazazi na wanafunzi', items: [{ name: 'Portali ya mzazi', note: 'Maendeleo, ada, kazi za nyumbani, matokeo' }, { name: 'Ujumbe', note: 'Mwalimu ↔ mzazi, kuhusu mwanafunzi mmoja' }, { name: 'SMS na matangazo', note: 'Darasa au shule nzima, gharama kwanza' }, { name: 'Vitambulisho', note: 'CR80 na picha na QR ya kuthibitisha' }] },
        { title: 'Fedha na wafanyakazi', items: [{ name: 'Ada', note: 'Muundo, risiti, taarifa, wadaiwa' }, { name: 'Uhasibu', note: 'Leja ya double-entry, taarifa ya mapato, mizania' }, { name: 'HR na mishahara', note: 'Likizo, mahudhurio ya wafanyakazi, payslip za PAYE/NSSF' }, { name: 'Maktaba, bweni, usafiri', note: 'Mengine yote ya kuendesha shule' }] },
      ],
    },
    documents: {
      kicker: 'Kinachotoka kwenye printa',
      title: 'Nyaraka ambazo shule inazikabidhi kweli.',
      lead: 'Kila moja ya hizi imetengenezwa na Shule SMS kutoka shule ya mfano — si michoro.',
      items: [
        { title: 'Ripoti ya mwanafunzi', body: 'Alama zenye uzito, daraja, pointi, nafasi, divisheni, wastani wa darasa, maoni na sahihi.' },
        { title: 'Karatasi ya matokeo ya darasa', body: 'Kila mwanafunzi na somo kwenye ukurasa mmoja, na nafasi na wastani wa masomo.' },
        { title: 'Payslip', body: 'Mshahara wa msingi, posho, NSSF, PAYE kwa viwango vya TRA, mshahara halisi na michango ya mwajiri.' },
        { title: 'Kitambulisho cha mwanafunzi', body: 'Picha, darasa, mlezi, na QR inayothibitisha mwenye kitambulisho kwenye simu yoyote.' },
      ],
    },
    steps: {
      kicker: 'Kuanza',
      title: 'Iko tayari kabla muhula haujaanza.',
      items: [
        ['Sajili shule', 'Tengeneza mwaka wa masomo na mihula, ongeza masomo na madarasa, weka kiwango cha madaraja. Ofisi inafanya hivi mara moja.'],
        ['Sajili wanafunzi, wazazi na walimu', 'Weka wanafunzi kwenye madarasa yao na uwaunganishe na walezi — ndugu wanashiriki rekodi moja ya mzazi. Mpe kila familia na kila mwalimu akaunti kwa kubofya mara moja.'],
        ['Endesha muhula', 'Walimu wanachukua mahudhurio na kuingiza alama. Mhasibu anarekodi ada. Wazazi wanapata SMS. Ripoti, payslip na taarifa zinachapishwa mwishoni.'],
      ],
    },
    trust: {
      kicker: 'Kumbukumbu zako, zikitunzwa vizuri',
      title: 'Imejengwa kama mfumo wa kumbukumbu rasmi, kwa sababu ndivyo ilivyo.',
      lead: 'Alama na fedha za shule si data ya majaribio. Kila badiliko la daraja au malipo linahusishwa na aliyelifanya, data ya kila shule imetenganishwa na ya nyingine, na shule yako inahifadhiwa nakala kila usiku.',
      items: [
        ['Rekodi ya ukaguzi', 'Nani alirekodi malipo, nani aliingiza alama, lini.'],
        ['Kutengana kwa shule', 'Shule moja haiwezi kamwe kusoma au kubadilisha rekodi za nyingine.'],
        ['Nakala kila usiku', 'Nakala kamili kila usiku, inayoweza kurejeshwa peke yake; data yako inatolewa ukiomba.'],
        ['Kusoma tu, kamwe giza', 'Usajili ukiisha, rekodi zinabaki kusomeka wakati unashughulikia.'],
      ],
    },
    pricing: {
      kicker: 'Bei',
      title: 'Bure kwa wanafunzi 50. Kisha bei kwa shule yako.',
      body: 'Bei inapangwa kutokana na idadi ya wanafunzi na ngazi unazofundisha — chekechea, msingi, O-level, A-level. Inalipwa kila mwezi kwa shilingi, kwa benki au pesa za simu.',
      hint: 'Kwa mfano: shule ya msingi ya wanafunzi 300 inalipa kwa mwezi chini ya ada ya muhula mmoja ya mwanafunzi mmoja. Hakuna malipo kwa mtumiaji, wala kwa ripoti au risiti.',
      cta: 'Bei inavyopangwa',
    },
    faq: {
      kicker: 'Maswali ambayo shule huuliza',
      title: 'Kabla hujapiga simu.',
      items: [
        ['Tunatunza kila kitu kwenye Excel. Tunaweza kuhamisha?', 'Ndiyo. Wanafunzi, walezi, wafanyakazi na muundo wa ada vinaingizwa kutoka spreadsheet, na tunafanya uhamisho wa kwanza pamoja nawe.'],
        ['Inafanya kazi intaneti ikiwa dhaifu au haipo?', 'Kurasa ni nyepesi kwa 3G na programu inasakinishwa kwenye simu. Mtandao ukikatika unaona ukurasa wa "offline" wa kweli badala ya kuzunguka; hakuna kilichoingizwa kinachopotea ukirudi mtandaoni.'],
        ['Data ni ya nani?', 'Ya shule. Data yako imetenganishwa na shule nyingine, inahifadhiwa nakala kila usiku, na inatolewa kwako ukiomba — hata ukiondoka.'],
        ['Tukiacha kulipa inakuwaje?', 'Hakuna kinachopotea. Shule inakuwa ya kusoma tu: kila rejista, alama na risiti inabaki kuonekana hadi ankara ilipwe, na kuandika kunarudi dakika ileile.'],
        ['Tunaweza kuiweka kwenye seva yetu?', 'Ndiyo — toleo la standalone linasakinishwa kwenye seva inayodhibitiwa na shule, bila usajili wala vizuizi. Bei kwa kila shule.'],
        ['Wazazi wanaitumiaje?', 'Wazazi wengi wanapokea SMS tu. Wanaotaka zaidi wanapata akaunti ya portali: matokeo yakishachapishwa, salio la ada, kazi za nyumbani, na ujumbe na mwalimu wa darasa.'],
      ],
    },
    finalCta: { title: 'Iione na wanafunzi wako mwenyewe kwenye skrini.', body: 'Demo inachukua dakika thelathini kwa video ya WhatsApp, kwa Kiswahili au Kiingereza. Leta karatasi ya alama ya muhula uliopita na tutachapisha ripoti kutoka humo.', whatsapp: 'Omba demo kwa WhatsApp', demo: 'Fungua shule ya mfano' },
  },
}
